stages:
  - build
  - test

#--------------------------
# Build templates
#--------------------------

.build-template: &build-template_definition
  stage: build
  script:
    - ci/fedora-packages.sh
    - ci/common-rpm-build.sh
    - mkdir ${CI_JOB_NAME}
    - cp -rv build/RPMS build/SRPMS ${CI_JOB_NAME}
    - tree ${CI_JOB_NAME}
  artifacts:
    paths:
      - "$CI_JOB_NAME"

#--------------------------
# Build jobs
#--------------------------

cc7:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  <<: *build-template_definition

centos8:
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  <<: *build-template_definition


#--------------------------
# Test jobs
#--------------------------

cc7-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  dependencies:
    - cc7
  script:
    - yum -y update
    - yum install -y cc7/RPMS/*/*.rpm
    - python test/functional/test_all.py

centos8-test:
  stage: test
  image: gitlab-registry.cern.ch/linuxsupport/c8-base
  dependencies:
    - centos8
  script:
    - dnf -y update
    - dnf -y install epel-release
    - cp ci/repo/dmc-gitlabci-el8.repo /etc/yum.repos.d
    - dnf install -y centos8/RPMS/*/*.rpm
    - python3 test/functional/test_all.py